LABELS = {
    "fr": {
        "title": "ChekScan - OCR Bancaire",
        "intro_title": "Numérisation Intelligente",
        "intro_text": "Déposez votre chèque et notre intelligence artificielle en extraira automatiquement les informations clés.",
        "upload_title": "Sélectionnez l'image du chèque",
        "upload_subtitle": "(Formats: JPG, PNG)",
        "upload_btn": "Parcourir",
        "submit_btn": "🔍 Lancer l'analyse OCR",
        "bot_welcome": "Bonjour ! Je suis l'assistant ChekScan. Je réponds à vos questions sur les chèques.",
        "bot_magic": "Soumettez un chèque pour voir la magie opérer !",
        "send": "Envoyer",
        "chat_placeholder": "Poser une question à l'IA...",
        "light_mode": "☀️ Mode Clair",
        "dark_mode": "🌙 Mode Sombre",
        "lang_ar": "العربية",
        "lang_fr": "Français",
        "history": "Historique",
        "new_scan": "Nouveau Scan",
        "scan_results": "Données Extrayées du Chèque",
        "filename": "Fichier :",
        "bank": "Banque",
        "amount": "Montant (MAD)",
        "payee": "Bénéficiaire (À l'ordre de)",
        "amount_words": "Montant en lettres",
        "place": "Lieu d'émission",
        "date": "Date",
        "micr": "Gencode (MICR)",
        "back_home": "Retour",
        "save_scan": "💾 Enregistrer le résultat",
        "history_title": "Historique des Scans",
        "no_history": "Aucun scan enregistré.",
        "chat_header": "🤖 Assistant IA (OpenRouter)",
        "dir": "ltr"
    },
    "ar": {
        "title": "شيك سكان - التعرف الضوئي",
        "intro_title": "رقمنة ذكية للشيكات",
        "intro_text": "قم برفع الشيك الخاص بك وسيقوم الذكاء الاصطناعي باستخراج المعلومات الأساسية تلقائيًا.",
        "upload_title": "اختر صورة الشيك",
        "upload_subtitle": "(الصيغ: JPG, PNG)",
        "upload_btn": "تصفح",
        "submit_btn": "🔍 بدء التحليل الضوئي",
        "bot_welcome": "مرحباً! أنا المساعد الذكي. يمكنك سؤالي عن أي شيء يخص الشيكات.",
        "bot_magic": "قم برفع الشيك لترى السحر!",
        "send": "إرسال",
        "chat_placeholder": "اسأل الذكاء الاصطناعي...",
        "light_mode": "☀️ وضع فاتح",
        "dark_mode": "🌙 وضع داكن",
        "lang_ar": "العربية",
        "lang_fr": "Français",
        "history": "السجل",
        "new_scan": "مسح جديد",
        "scan_results": "البيانات المستخرجة",
        "filename": "الملف :",
        "bank": "البنك",
        "amount": "المبلغ (درهم)",
        "payee": "المستفيد (لأمر)",
        "amount_words": "المبلغ بالحروف",
        "place": "مكان الإصدار",
        "date": "التاريخ",
        "micr": "الشريط المغناطيسي",
        "back_home": "رجوع",
        "save_scan": "💾 حفظ النتيجة",
        "history_title": "سجل الشيكات",
        "no_history": "لا توجد شيكات محفوظة.",
        "chat_header": "🤖 المساعد الذكي (OpenRouter)",
        "dir": "rtl"
    }
}
